name: Test Actions
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build the setup
    runs-on: ubuntu-latest
    steps:
      - name: Test stuff
        run: |
          ls ./
          pwd
          sudo apt-get update
          sudo apt-get install apache2
          composer global require SU-SWS/stanford-caravan:dev-8.x-1.x
          sudo chmod -R 777 /var/www
          rm -rf /var/www/*
          ~/.composer/vendor/bin/sws-caravan phpunit /var/www/ --extension-dir=/var/www/test --with-coverage
