name: Test Actions
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build the setup
    runs-on: ubuntu-latest
    services:
      drupal8ci:
        image: pookmish/drupal8ci:latest
    steps:
      - name: Test stuff
        run: |
          pwd
          ls /var/www
          curl localhost
#          pwd
#          echo "-   home   -"
#          ls ~/
#          echo "-   work   -"
#          ls ~/work
#          echo "-   actions   -"
#          ls ~/work/test_github_actions/test_github_actions
#          sudo apt-get update
#          sudo apt-get install apache2
#          composer global require SU-SWS/stanford-caravan:dev-8.x-1.x
#          sudo chmod -R 777 /var/www
#          rm -rf /var/www/*
#          ~/.composer/vendor/bin/sws-caravan phpunit /var/www/ --extension-dir=~/work/test_github_actions/test_github_actions --with-coverage
