on: [push, pull_request]
name: Tests and code
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:pcov

    services:
      mariadb:
        image: quay.io/juampynr/drupal8-github-actions:latest
        ports:
          - 33306:3306

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run PHPUnit tests
        run: |
          composer global config minimum-stability dev
          composer global require SU-SWS/stanford-caravan:dev-8.x-1.x
          ~/.composer/vendor/bin/sws-caravan phpunit /var/www/html --extension-dir=$GITHUB_WORKSPACE --with-coverage
