name: Test Actions
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build the setup
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:latest
      ports:
        - 80
        - 8080
    services:
      mariadb:
        image: mariadb:1.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
    steps:
      - name: Test stuff
        run: |
          pwd
          ls /var/www/html
          mkdir /var/www/html/docroot
          echo '<h1>Hi</h1>' > /var/www/html/docroot/index.html
          apachectl stop
          apachectl start
          curl localhost
          php -v
          mysql -u root -e "show databases"
#          pwd
#          echo "-   home   -"
#          ls ~/
#          echo "-   work   -"
#          ls ~/work
#          echo "-   actions   -"
#          ls ~/work/test_github_actions/test_github_actions
#          sudo apt-get update
#          sudo apt-get install apache2
#          composer global require SU-SWS/stanford-caravan:dev-8.x-1.x
#          sudo chmod -R 777 /var/www
#          rm -rf /var/www/*
#          ~/.composer/vendor/bin/sws-caravan phpunit /var/www/ --extension-dir=~/work/test_github_actions/test_github_actions --with-coverage
