name: Test Actions
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build the setup
    runs-on: ubuntu-latest
    steps:
      - name: Show the word dir
        run: |
          apache2ctl stop
          apache2ctl start
          ls /var
          php -r 'phpinfo();'
          curl localhost
